<a href="https://colab.research.google.com/github/diotte-am/2024-RT-107_diotte-am/blob/main/ACT_343_3_2_Pandas_Dataframe_Exercises_Movie_Data_Analysis_with_Pandas_diotte_am.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Amare Diotte
Data Engineering
ACT 343.3.2
Pandas Dataframe Exercises: Movie Data Analysis with Pandas

#**ACT - 343.3.2 Pandas Dataframe Exercises: Movie Data Analysis with Pandas**

##**Assignment Overview:**

In this assignment, you will be working with simple and easy questions for practicing with the Pandas library using the provided movie dataset:


**Scenario:**
You are a movie analyst and you have a dataset containing information about movies, including their titles, genres, release years, and IMDB ratings. Your task is to use Pandas to analyze this data and answer some interesting questions.

**Common methods used with Pandas Series**

.head(), .mean(), .sort_values(), .info(), .describe(), .value_counts(), .groupby()

Please refer to the P[andas Dataframe](https://pandas.pydata.org/docs/reference/frame.html) Documentation for a full list of methods and how to implement them.

##**Instructions:**


**Task 1: Here we have a sample movie dataset. Using the pandas library, convert the list of dictionaries into a Pandas DataFrame.**

Dataset contains the following columns:

- title (string): The title of the movie.

- genre (string): The genre of the movie (e.g., comedy, drama, action).

- release_year (int): The year the movie was released
-imdb_rating (float): The IMDB rating of the movie (on a scale of 1 to 10)

In [1]:
# Sample movie data with 50 entries
movie_data = [
    {"title": "The Shawshank Redemption", "genre": "Drama", "release_year": 1994, "imdb_rating": 9.3},
    {"title": "The Godfather", "genre": "Crime", "release_year": 1972, "imdb_rating": 9.2},
    {"title": "The Dark Knight", "genre": "Action", "release_year": 2008, "imdb_rating": 9.0},
    {"title": "12 Angry Men", "genre": "Drama", "release_year": 1957, "imdb_rating": 8.9},
    {"title": "Schindler's List", "genre": "Biography", "release_year": 1993, "imdb_rating": 8.9},
    {"title": "Pulp Fiction", "genre": "Crime", "release_year": 1994, "imdb_rating": 8.9},
    {"title": "The Lord of the Rings: The Return of the King", "genre": "Adventure", "release_year": 2003, "imdb_rating": 8.9},
    {"title": "The Good, the Bad and the Ugly", "genre": "Western", "release_year": 1966, "imdb_rating": 8.8},
    {"title": "Fight Club", "genre": "Drama", "release_year": 1999, "imdb_rating": 8.8},
    {"title": "Forrest Gump", "genre": "Drama", "release_year": 1994, "imdb_rating": 8.8},
    {"title": "Inception", "genre": "Action", "release_year": 2010, "imdb_rating": 8.8},
    {"title": "The Matrix", "genre": "Sci-Fi", "release_year": 1999, "imdb_rating": 8.7},
    {"title": "Goodfellas", "genre": "Biography", "release_year": 1990, "imdb_rating": 8.7},
    {"title": "One Flew Over the Cuckoo's Nest", "genre": "Drama", "release_year": 1975, "imdb_rating": 8.7},
    {"title": "Se7en", "genre": "Crime", "release_year": 1995, "imdb_rating": 8.6},
    {"title": "The Silence of the Lambs", "genre": "Thriller", "release_year": 1991, "imdb_rating": 8.6},
    {"title": "Saving Private Ryan", "genre": "Drama", "release_year": 1998, "imdb_rating": 8.6},
    {"title": "City of God", "genre": "Crime", "release_year": 2002, "imdb_rating": 8.6},
    {"title": "Life Is Beautiful", "genre": "Comedy", "release_year": 1997, "imdb_rating": 8.6},
    {"title": "The Usual Suspects", "genre": "Crime", "release_year": 1995, "imdb_rating": 8.5},
    {"title": "Léon: The Professional", "genre": "Action", "release_year": 1994, "imdb_rating": 8.5},
    {"title": "Interstellar", "genre": "Adventure", "release_year": 2014, "imdb_rating": 8.6},
    {"title": "Spirited Away", "genre": "Animation", "release_year": 2001, "imdb_rating": 8.6},
    {"title": "Parasite", "genre": "Drama", "release_year": 2019, "imdb_rating": 8.6},
    {"title": "The Green Mile", "genre": "Crime", "release_year": 1999, "imdb_rating": 8.6},
    {"title": "Star Wars: Episode V - The Empire Strikes Back", "genre": "Action", "release_year": 1980, "imdb_rating": 8.7},
    {"title": "The Pianist", "genre": "Biography", "release_year": 2002, "imdb_rating": 8.5},
    {"title": "The Intouchables", "genre": "Biography", "release_year": 2011, "imdb_rating": 8.5},
    {"title": "The Departed", "genre": "Crime", "release_year": 2006, "imdb_rating": 8.5},
    {"title": "Terminator 2: Judgment Day", "genre": "Action", "release_year": 1991, "imdb_rating": 8.5},
    {"title": "Back to the Future", "genre": "Adventure", "release_year": 1985, "imdb_rating": 8.5},
    {"title": "Whiplash", "genre": "Drama", "release_year": 2014, "imdb_rating": 8.5},
    {"title": "Gladiator", "genre": "Action", "release_year": 2000, "imdb_rating": 8.5},
    {"title": "The Prestige", "genre": "Drama", "release_year": 2006, "imdb_rating": 8.5},
    {"title": "The Lion King", "genre": "Animation", "release_year": 1994, "imdb_rating": 8.5},
    {"title": "Memento", "genre": "Mystery", "release_year": 2000, "imdb_rating": 8.4},
    {"title": "Apocalypse Now", "genre": "Drama", "release_year": 1979, "imdb_rating": 8.4},
    {"title": "Alien", "genre": "Horror", "release_year": 1979, "imdb_rating": 8.4},
    {"title": "Sunset Blvd.", "genre": "Drama", "release_year": 1950, "imdb_rating": 8.4},
    {"title": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", "genre": "Comedy", "release_year": 1964, "imdb_rating": 8.4},
    {"title": "The Great Dictator", "genre": "Comedy", "release_year": 1940, "imdb_rating": 8.4},
    {"title": "Cinema Paradiso", "genre": "Drama", "release_year": 1988, "imdb_rating": 8.4},
    {"title": "The Lives of Others", "genre": "Drama", "release_year": 2006, "imdb_rating": 8.4},
    {"title": "Grave of the Fireflies", "genre": "Animation", "release_year": 1988, "imdb_rating": 8.5},
    {"title": "Paths of Glory", "genre": "Drama", "release_year": 1957, "imdb_rating": 8.4},
    {"title": "Django Unchained", "genre": "Drama", "release_year": 2012, "imdb_rating": 8.4},
    {"title": "WALL·E", "genre": "Animation", "release_year": 2008, "imdb_rating": 8.4},
    {"title": "American Beauty", "genre": "Drama", "release_year": 1999, "imdb_rating": 8.4},
    {"title": "The Dark Knight Rises", "genre": "Action", "release_year": 2012, "imdb_rating": 8.4}
]

In [3]:
#Load the data into a pandas DataFrame
import pandas as pd
import numpy as np

**Task 2: Basic Information:**

How do you get a concise summary of the DataFrame, including the number of non-null entries for each column?

In [4]:
df = pd.DataFrame(movie_data)
df

,title,genre,release_year,imdb_rating
0,The Shawshank Redemption,Drama,1994,9.3
1,The Godfather,Crime,1972,9.2
2,The Dark Knight,Action,2008,9.0
3,12 Angry Men,Drama,1957,8.9
4,Schindler's List,Biography,1993,8.9
5,Pulp Fiction,Crime,1994,8.9
6,The Lord of the Rings: The Return of the King,Adventure,2003,8.9
7,"The Good, the Bad and the Ugly",Western,1966,8.8
8,Fight Club,Drama,1999,8.8
9,Forrest Gump,Drama,1994,8.8
10,Inception,Action,2010,8.8
11,The Matrix,Sci-Fi,1999,8.7
12,Goodfellas,Biography,1990,8.7
13,One Flew Over the Cuckoo's Nest,Drama,1975,8.7
14,Se7en,Crime,1995,8.6
15,The Silence of the Lambs,Thriller,1991,8.6
16,Saving Private Ryan,Drama,1998,8.6
17,City of God,Crime,2002,8.6
18,Life Is Beautiful,Comedy,1997,8.6
19,The Usual Suspects,Crime,1995,8.5
20,Léon: The Professional,Action,1994,8.5
21,Interstellar,Adventure,2014,8.6
22,Spirited Away,Animation,2001,8.6
23,Parasite,Drama,2019,8.6
24,The Green Mile,Crime,1999,8.6
25,Star Wars: Episode V - The Empire Strikes Back,Action,1980,8.7
26,The Pianist,Biography,2002,8.5
27,The Intouchables,Biography,2011,8.5
28,The Departed,Crime,2006,8.5
29,Terminator 2: Judgment Day,Action,1991,8.5
30,Back to the Future,Adventure,1985,8.5
31,Whiplash,Drama,2014,8.5
32,Gladiator,Action,2000,8.5
33,The Prestige,Drama,2006,8.5
34,The Lion King,Animation,1994,8.5
35,Memento,Mystery,2000,8.4
36,Apocalypse Now,Drama,1979,8.4
37,Alien,Horror,1979,8.4
38,Sunset Blvd.,Drama,1950,8.4
39,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy,1964,8.4
40,The Great Dictator,Comedy,1940,8.4
41,Cinema Paradiso,Drama,1988,8.4
42,The Lives of Others,Drama,2006,8.4
43,Grave of the Fireflies,Animation,1988,8.5
44,Paths of Glory,Drama,1957,8.4
45,Django Unchained,Drama,2012,8.4
46,WALL·E,Animation,2008,8.4
47,American Beauty,Drama,1999,8.4
48,The Dark Knight Rises,Action,2012,8.4

**Task 3: Check the DataFrame:**
Print the first few rows of the DataFrame using the `head()` method to get an idea of the data.

In [5]:
df.head(3)

                      title   genre  release_year  imdb_rating
0  The Shawshank Redemption   Drama          1994          9.3
1             The Godfather   Crime          1972          9.2
2           The Dark Knight  Action          2008          9.0

**Task 4: Selecting Columns:**

How can you select and display only the title and imdb_rating columns?

In [10]:
print(df[['title','imdb_rating']])

                                                title  imdb_rating
0                            The Shawshank Redemption          9.3
1                                       The Godfather          9.2
2                                     The Dark Knight          9.0
3                                        12 Angry Men          8.9
4                                    Schindler's List          8.9
5                                        Pulp Fiction          8.9
6       The Lord of the Rings: The Return of the King          8.9
7                      The Good, the Bad and the Ugly          8.8
8                                          Fight Club          8.8
9                                        Forrest Gump          8.8
10                                          Inception          8.8
11                                         The Matrix          8.7
12                                         Goodfellas          8.7
13                    One Flew Over the Cuckoo's Nest          8.7
14                                              Se7en          8.6
15                           The Silence of the Lambs          8.6
16                                Saving Private Ryan          8.6
17                                        City of God          8.6
18                                  Life Is Beautiful          8.6
19                                 The Usual Suspects          8.5
20                             Léon: The Professional          8.5
21                                       Interstellar          8.6
22                                      Spirited Away          8.6
23                                           Parasite          8.6
24                                     The Green Mile          8.6
25     Star Wars: Episode V - The Empire Strikes Back          8.7
26                                        The Pianist          8.5
27                                   The Intouchables          8.5
28                                       The Departed          8.5
29                         Terminator 2: Judgment Day          8.5
30                                 Back to the Future          8.5
31                                           Whiplash          8.5
32                                          Gladiator          8.5
33                                       The Prestige          8.5
34                                      The Lion King          8.5
35                                            Memento          8.4
36                                     Apocalypse Now          8.4
37                                              Alien          8.4
38                                       Sunset Blvd.          8.4
39  Dr. Strangelove or: How I Learned to Stop Worr...          8.4
40                                 The Great Dictator          8.4
41                                    Cinema Paradiso          8.4
42                                The Lives of Others          8.4
43                             Grave of the Fireflies          8.5
44                                     Paths of Glory          8.4
45                                   Django Unchained          8.4
46                                             WALL·E          8.4
47                                    American Beauty          8.4
48                              The Dark Knight Rises          8.4

**Task 5: Filtering Rows:**

How do you filter the DataFrame to show only movies with an IMDb rating greater than 9.0?

In [11]:
df[df['imdb_rating'] > 9.0]

                      title  genre  release_year  imdb_rating
0  The Shawshank Redemption  Drama          1994          9.3
1             The Godfather  Crime          1972          9.2

**Task 6: Sorting Data:**

How can you sort the DataFrame by `release_year` in ascending order?

In [13]:
df.sort_values('release_year')

,title,genre,release_year,imdb_rating
40,The Great Dictator,Comedy,1940,8.4
38,Sunset Blvd.,Drama,1950,8.4
44,Paths of Glory,Drama,1957,8.4
3,12 Angry Men,Drama,1957,8.9
39,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy,1964,8.4
7,"The Good, the Bad and the Ugly",Western,1966,8.8
1,The Godfather,Crime,1972,9.2
13,One Flew Over the Cuckoo's Nest,Drama,1975,8.7
36,Apocalypse Now,Drama,1979,8.4
37,Alien,Horror,1979,8.4
25,Star Wars: Episode V - The Empire Strikes Back,Action,1980,8.7
30,Back to the Future,Adventure,1985,8.5
43,Grave of the Fireflies,Animation,1988,8.5
41,Cinema Paradiso,Drama,1988,8.4
12,Goodfellas,Biography,1990,8.7
29,Terminator 2: Judgment Day,Action,1991,8.5
15,The Silence of the Lambs,Thriller,1991,8.6
4,Schindler's List,Biography,1993,8.9
20,Léon: The Professional,Action,1994,8.5
9,Forrest Gump,Drama,1994,8.8
5,Pulp Fiction,Crime,1994,8.9
34,The Lion King,Animation,1994,8.5
0,The Shawshank Redemption,Drama,1994,9.3
14,Se7en,Crime,1995,8.6
19,The Usual Suspects,Crime,1995,8.5
18,Life Is Beautiful,Comedy,1997,8.6
16,Saving Private Ryan,Drama,1998,8.6
24,The Green Mile,Crime,1999,8.6
47,American Beauty,Drama,1999,8.4
8,Fight Club,Drama,1999,8.8
11,The Matrix,Sci-Fi,1999,8.7
32,Gladiator,Action,2000,8.5
35,Memento,Mystery,2000,8.4
22,Spirited Away,Animation,2001,8.6
17,City of God,Crime,2002,8.6
26,The Pianist,Biography,2002,8.5
6,The Lord of the Rings: The Return of the King,Adventure,2003,8.9
42,The Lives of Others,Drama,2006,8.4
28,The Departed,Crime,2006,8.5
33,The Prestige,Drama,2006,8.5
2,The Dark Knight,Action,2008,9.0
46,WALL·E,Animation,2008,8.4
10,Inception,Action,2010,8.8
27,The Intouchables,Biography,2011,8.5
45,Django Unchained,Drama,2012,8.4
48,The Dark Knight Rises,Action,2012,8.4
21,Interstellar,Adventure,2014,8.6
31,Whiplash,Drama,2014,8.5
23,Parasite,Drama,2019,8.6

**Task 7: Average IMDb Rating:**

How do you calculate the average IMDb rating of all movies in the DataFrame?

In [14]:
df['imdb_rating'].mean()

8.60612244897959

**Task 8: Specific Year Filter:**

How can you filter the DataFrame to show only movies released in the year 1994?

In [15]:
df[df['release_year'] == 1994]

                       title      genre  release_year  imdb_rating
0   The Shawshank Redemption      Drama          1994          9.3
5               Pulp Fiction      Crime          1994          8.9
9               Forrest Gump      Drama          1994          8.8
20    Léon: The Professional     Action          1994          8.5
34             The Lion King  Animation          1994          8.5

**Task 9:Average rating by genre**:
Group the DataFrame by genre and calculate the average IMDB rating for each genre using the `groupby()` and `mean()` methods.

In [18]:
# method 1
df['imdb_rating'].groupby(df['genre']).mean()

# method 2
df.groupby('genre').mean('imdb_rating')

           release_year  imdb_rating
genre
Action      1999.285714     8.628571
Adventure   2000.666667     8.666667
Animation   1997.750000     8.500000
Biography   1999.000000     8.650000
Comedy      1967.000000     8.466667
Crime       1994.714286     8.700000
Drama       1990.437500     8.593750
Horror      1979.000000     8.400000
Mystery     2000.000000     8.400000
Sci-Fi      1999.000000     8.700000
Thriller    1991.000000     8.600000
Western     1966.000000     8.800000

**Task 10:Top 10 rated movies:**

Sort the DataFrame by IMDB rating in descending order and select the top 10 movies using `sort_values()` and `head()` methods

In [23]:
top_ten = df.sort_values('imdb_rating', ascending=False).head(10)
top_ten

,title,genre,release_year,imdb_rating
0,The Shawshank Redemption,Drama,1994,9.3
1,The Godfather,Crime,1972,9.2
2,The Dark Knight,Action,2008,9.0
3,12 Angry Men,Drama,1957,8.9
4,Schindler's List,Biography,1993,8.9
5,Pulp Fiction,Crime,1994,8.9
6,The Lord of the Rings: The Return of the King,Adventure,2003,8.9
10,Inception,Action,2010,8.8
9,Forrest Gump,Drama,1994,8.8
8,Fight Club,Drama,1999,8.8

**Task 11: Number of movies by release decade:**
Create new groups based on decades using integer division (//) and calculate the number of movies released in each decade using the groupby and size methods.

In [40]:
df['decade'] = (df['release_year'] // 10) * 10
print(df.groupby('decade').size())
df

decade
1940     1
1950     3
1960     2
1970     4
1980     4
1990    17
2000    11
2010     7
dtype: int64

,title,genre,release_year,imdb_rating,decade
0,The Shawshank Redemption,Drama,1994,9.3,1990
1,The Godfather,Crime,1972,9.2,1970
2,The Dark Knight,Action,2008,9.0,2000
3,12 Angry Men,Drama,1957,8.9,1950
4,Schindler's List,Biography,1993,8.9,1990
5,Pulp Fiction,Crime,1994,8.9,1990
6,The Lord of the Rings: The Return of the King,Adventure,2003,8.9,2000
7,"The Good, the Bad and the Ugly",Western,1966,8.8,1960
8,Fight Club,Drama,1999,8.8,1990
9,Forrest Gump,Drama,1994,8.8,1990
10,Inception,Action,2010,8.8,2010
11,The Matrix,Sci-Fi,1999,8.7,1990
12,Goodfellas,Biography,1990,8.7,1990
13,One Flew Over the Cuckoo's Nest,Drama,1975,8.7,1970
14,Se7en,Crime,1995,8.6,1990
15,The Silence of the Lambs,Thriller,1991,8.6,1990
16,Saving Private Ryan,Drama,1998,8.6,1990
17,City of God,Crime,2002,8.6,2000
18,Life Is Beautiful,Comedy,1997,8.6,1990
19,The Usual Suspects,Crime,1995,8.5,1990
20,Léon: The Professional,Action,1994,8.5,1990
21,Interstellar,Adventure,2014,8.6,2010
22,Spirited Away,Animation,2001,8.6,2000
23,Parasite,Drama,2019,8.6,2010
24,The Green Mile,Crime,1999,8.6,1990
25,Star Wars: Episode V - The Empire Strikes Back,Action,1980,8.7,1980
26,The Pianist,Biography,2002,8.5,2000
27,The Intouchables,Biography,2011,8.5,2010
28,The Departed,Crime,2006,8.5,2000
29,Terminator 2: Judgment Day,Action,1991,8.5,1990
30,Back to the Future,Adventure,1985,8.5,1980
31,Whiplash,Drama,2014,8.5,2010
32,Gladiator,Action,2000,8.5,2000
33,The Prestige,Drama,2006,8.5,2000
34,The Lion King,Animation,1994,8.5,1990
35,Memento,Mystery,2000,8.4,2000
36,Apocalypse Now,Drama,1979,8.4,1970
37,Alien,Horror,1979,8.4,1970
38,Sunset Blvd.,Drama,1950,8.4,1950
39,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy,1964,8.4,1960
40,The Great Dictator,Comedy,1940,8.4,1940
41,Cinema Paradiso,Drama,1988,8.4,1980
42,The Lives of Others,Drama,2006,8.4,2000
43,Grave of the Fireflies,Animation,1988,8.5,1980
44,Paths of Glory,Drama,1957,8.4,1950
45,Django Unchained,Drama,2012,8.4,2010
46,WALL·E,Animation,2008,8.4,2000
47,American Beauty,Drama,1999,8.4,1990
48,The Dark Knight Rises,Action,2012,8.4,2010